worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /module1 {
            proxy_pass http://module1:5001;
        }

        location /module2 {
            proxy_pass http://module2:5002;
        }

        location /module3 {
            proxy_pass http://module3:5003;
        }
    }
}
